# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on: ["push"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: go test
        run: |
          go test ./... -count 1
